### ISSUE TITLE
Question about EOS

### ISSUE THREAD

**Issue by SophiaAtkinson** [danielbrendel/steamwidgets-js#1]
I had a question about the end of steamwidgets.com, Does this mean the API will go offline? If so is there a self-hosted drop-in replacement?

**Comment by danielbrendel** [comment]
Hi, initially this was the impact due to some hosting problems. Currently I try to save it, but I didn't hear back from the hosting provider yet. Problem is the domain expires tomorrow due to an error and I can't say for sure whether it will be saved in time. At a last resort I hope I can get it back during grace period.
I'll keep this issue updated once I hear back from my hosting provider.

**Comment by danielbrendel** [comment]
I am happy to announce that I managed to save the domain and the problem was solved. The service (API, backend, npm package) will stay online and available!

**Comment by SophiaAtkinson** [comment]
Is there a way to host the API on my own servers as well?

**Comment by danielbrendel** [comment]
You can fork the Steamwidgets backend and make your own API backend if you want: https://github.com/danielbrendel/steamwidgets-web

Or directly query the Steam Web API and render the results in your website: https://steamcommunity.com/dev?l=english

**Comment by raybun** [comment]
@danielbrendel FYI, visiting the domain now seems to redirect to some adware site

**Comment by danielbrendel** [comment]
Yeah, I have to remove it from the repo details. The domain was canceled and after beeing made publicly available by the responsible domain registry, it got registered by a domain grabber. They like to grab domains that had some traffic before.

**Comment by SophiaAtkinson** [comment]
@raybun I have a mirror that you can use, https://steam.satki.net
